name: Azure Static Web Apps pluz Azure Function API

on:
  push:
    branches:
      - dev

env:
  AZ_SWA_RG: "RG-DEV-STATIC-WEB-APP"
  AZ_SWA: "swa-az-func-v2" 

jobs:
  build_and_deploy_job:
    name: "SWA Build, Deploy and Configure"
    runs-on: ubuntu-latest
    environment: development # needed for OIDC (EntraID)
    # In GitHub workflow, you should set permissions: with id-token: write at workflow or job level
    permissions:
      contents: read  # Required for actions/checkout
      id-token: write # Required for OIDC
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v5
        with:
          submodules: true
          lfs: false

      - name: "SWA Build And Deploy"
        id: builddeploy
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_HILL_06A27A503 }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "src" # App source code path
          api_location: "api" # Api source code path - optional
          # output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        # env: # Add environment variables here
        #   AZURE_ENVIRONMENT: ""
        #   TWELVEDATA_API_KEY: ""

      # Below two tasks are needed for setting up environment variables in SWA
      - name: "Azure CLI login"
        uses: azure/login@v2
        with:
          # for CLIENT_ID check EntraID App registrations (Certificate & secrets)
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}

      - name: "SWA Config"
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az staticwebapp appsettings set -g "${{ env.AZ_SWA_RG }}" -n "${{ env.AZ_SWA }}" --setting-names \
              AZURE_ENVIRONMENT="${{ secrets.AZURE_ENVIRONMENT }}" \
              TWELVEDATA_API_KEY="${{ secrets.TWELVEDATA_API_KEY }}"