name: Azure Static Web Apps pluz Azure Function API

on:
  push:
    branches:
      - dev

env:
  AZ_SWA_RG: "RG-DEV-STATIC-WEB-APP"
  AZ_SWA: "swa-az-func-v2"

# Add "id-token" with the intended permissions (Azure Authentication)
permissions:
  contents: read
  id-token: write

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: "SWA Build, Deploy and Configure"
    environment: development
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: "SWA Build And Deploy"
        id: builddeploy
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_HILL_06A27A503 }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "src" # App source code path
          api_location: "api" # Api source code path - optional
          # output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        # env: # Add environment variables here
        #   AZURE_ENVIRONMENT: ${{ secrets.AZURE_ENVIRONMENT }}
        #   TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}

      - name: 'Azure CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}

      - name: "SWA Config"
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az staticwebapp appsettings set -g "${{ env.AZ_SWA_RG }}" -n "${{ env.AZ_SWA }}" --setting-names \
              AZURE_ENVIRONMENT="${{ secrets.AZURE_ENVIRONMENT }}" \
              TWELVEDATA_API_KEY="${{ secrets.TWELVEDATA_API_KEY }}"